
name: Autograding Tests MerSof
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compilaci贸n ejercicio1
      id: compilacion-ejercicio1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilaci贸n ejercicio1
        setup-command: pip install -r requirements.txt
        command: python -m py_compile src/ejercicio1.py
        timeout: 3600
        max-score: 25
    - name: Compilaci贸n ejercicio2
      id: compilacion-ejercicio2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilaci贸n ejercicio2
        setup-command: ''
        command: python -m py_compile src/ejercicio2.py
        timeout: 3600
        max-score: 25
    - name: Pruebas ejercicio1
      id: pruebas-ejercicio1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Pruebas ejercicio1
        setup-command: ''
        command: python -m pytest tests/test_ejercicio1.py
        timeout: 3600
        max-score: 25
    - name: Pruebas ejercicio2
      id: pruebas-ejercicio2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Pruebas ejercicio2
        setup-command: ''
        command: python -m pytest tests/test_ejercicio2.py
        timeout: 3600
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILACION-EJERCICIO1_RESULTS: "${{steps.compilacion-ejercicio1.outputs.result}}"
        COMPILACION-EJERCICIO2_RESULTS: "${{steps.compilacion-ejercicio2.outputs.result}}"
        PRUEBAS-EJERCICIO1_RESULTS: "${{steps.pruebas-ejercicio1.outputs.result}}"
        PRUEBAS-EJERCICIO2_RESULTS: "${{steps.pruebas-ejercicio2.outputs.result}}"
      with:
        runners: compilacion-ejercicio1,compilacion-ejercicio2,pruebas-ejercicio1,pruebas-ejercicio2
