
name: Autograding Tests MerSof
'on':
 - push
 - pull_request
 - repository_dispatch
 
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Compilaci贸n ejercicio1
      id: compilacion-ejercicio1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilaci贸n ejercicio1
        setup-command: pip install -r requirements.txt
        command: python -m py_compile src/ejercicio1.py
        timeout: 3600
        max-score: 25
    - name: Compilaci贸n ejercicio2
      id: compilacion-ejercicio2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Compilaci贸n ejercicio2
        setup-command: ''
        command: python -m py_compile src/ejercicio2.py
        timeout: 3600
        max-score: 25
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        COMPILACION-EJERCICIO1_RESULTS: "${{steps.compilacion-ejercicio1.outputs.result}}"
        COMPILACION-EJERCICIO2_RESULTS: "${{steps.compilacion-ejercicio2.outputs.result}}"
      with:
        runners: compilacion-ejercicio1,compilacion-ejercicio2
        
  codacy-coverage:
     name: Codacy Coverage Report
     runs-on: ubuntu-latest

     steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests with coverage
        run: |
          coverage run -m pytest
          coverage xml

      - name: Upload coverage to Codacy
        run: |
          curl -Ls https://coverage.codacy.com/get.sh | sh
        env:
          CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
